### ISSUE TITLE
Content Hosting Configuration handling uplift in 5GMSd AF

### ISSUE THREAD

**Issue by rjb1000** [5G-MAG/rt-5gms-application-function#19]
# Context

The syntax of the Content Hosting Configuration has been modified to take into account implementation feedback from 5G-MAG:
- 5G-MAG/Standards#16
- 5G-MAG/Standards#17
- 5G-MAG/Standards#18
- 5G-MAG/Standards#19
- 5G-MAG/Standards#27
- 5G-MAG/Standards#28
- 5G-MAG/Standards#29

The purpose of this issue is to modify the handling of the Content Hosting Configuration in the 5GMSd AF.

# Specification

TS 26.512 V17.3.0 includes an updated `TS26512_M1_ContentHostingProvisioning.yaml` in annex C.3.5. The internal data structures in the 5GMS AF need to be adjusted to take into account these changes, namely:
- `IngestConfiguration.path` and `IngestConfiguration.entryPoint` replaced by `IngestConfiguration.baseURL`.
- `DistributionConfiguration.baseURL` added. (Assigned by the 5GMSd AF.)
- `DistributionConfiguration.supplementaryDistributionNetworks` redefined. (Rel-17 and later only.)
- `PathRewriteRule.requestPattern` renamed to `PathRewriteRules.requestPathPattern`.
- `ContentHostingConfiguration.entryPointPath` added. (Appended to `DistributionConfiguration.baseURL` to populate `streamingAccess.mediaPlayerEntry` in the M5d Service Access Information.)

**Comment by davidjwbbc** [comment]
The `ContentHostingConfiguration.entryPointPath`, as defined in the proposal for v17.3.0, is a string with the `uri` format.

However, due to an ambiguity in the OpenAPI and JSON Schema specifications the `uri` format can be interpreted as the all encompassing URI format as described in RFC 3986 or could refer to the `URI` ABNF term defined in RFC 3986, which is more restrictive and requires a scheme to be present. The latter interpretation is not suitable for the `ContentHostingConfiguration.entryPointPath` which is intended to be a relative path only.

Unfortunately for us the JSON schema engine used by the openapi-generator interprets the `uri` format as the more restrictive `URI` ABNF definition, and other OpenAPI processors may also do the same. Therefore we have raised an [issue on the Standards repository](5G-MAG/Standards#36) to address this ambiguity in the `uri` format in the TS 26.512 OpenAPI YAML by using the `uri-reference` format instead.

Tests on openapi-generator show that the `uri-reference` format is ignored and the property is then treated as a simple string. Therefore it would be prudent to enforce a string that looks like a URL path with optional query and fragment on the `ContentHostingConfiguration.entryPointPath` inside the 5GMS application function.

Therefore, as part of this ticket, the 5GMS Application Function should check the value in the `ContentHostingConfiguration.entryPointPath`, once the structure has been parsed by the openapi-generator model, to make sure it conforms to the format of a URL path.

This can be done by using the GNU C Library POSIX regex functions defined in regexp.h (old file name, now deprecated) or regex.h (new name for regexp.h). The regex `^[^/#?:]{1,}(/[^#?/]{1,})*(\?[^#]*)?(#.*)?$` should suffice to check that the format is a relative path if `REG_EXTENDED` is supplied to the `regcomp()` function as a flag.

**Comment by devbbc** [comment]
Using the regex `^[^/#?:]{1,}(/[^#?/]{1,})*(\?[^#]*)?(#.*)?` with GNU C Library POSIX regex functions sometimes throw syntax errors as this express does not escape `\?` . To avoid this syntax error, the expression has to be `^[^/#?:]{1,}(/[^#?/]{1,})*(\\?[^#]*)?(#.*)?$`

**Comment by rjb1000** [comment]
The Change Requests for TS 26.512 were approved at SA#98-e last week. Publication of V17.3.0 will follow soon.

(Full details on the seven issues linked from the _Context_ section in the main issue description above.)

**Comment by devbbc** [comment]
Uplifted `contentHostingConfiguration` to TS 26.512 V17.3.0. The AF Can now parse and validate the uplifted  `contentHostingConfiguration` from a file and store in its internal data structure. The next step is to provision `contentHostingConfiguration` through the M1 interface.

**Comment by davidjwbbc** [comment]
Taken @devbbc's work from above and pushed to a ["feature/uplift-to-ts26-512-v17-3-0" branch on my fork of rt-5gms-application-function]() along with some bug fixes (including one for the segfault @jordijoangimenez was seeing). I've tested against the same branch in my fork of rt-5gms-application-server and it seems to work. I'll do a bit more testing before I submit the PR for this.
