### ISSUE TITLE
Error due to not accesible Certificates.json

### ISSUE THREAD

**Issue by stojkovicv** [5G-MAG/rt-5gms-application-function#49]
When trying to run AF with `/usr/local/bin/open5gs-msafd` the several errors occur showing that path for accessing `Certificates.json` is broken, and that directory, which should contain it - doesn't exist.

It's supposed to be located at `/usr/local/etc/open5gs/.../.../examples/Certificate.json`, however after installation, `open5gs` folder contains only .yaml files.
After modifying `certificate` and `contentHostingConfiguration` properties of `msaf.yaml` to point to resources in cloned repository (`example` directory), AF works.

Question is why those resources are not configured within the system after installation? Is it intended at this phase that paths must be tuned manually?

**Comment by stepski011** [comment]
For now, proposed solution is to change full paths for `certificate` and `contentHostingConfiguration` properties directly inside of `msaf.yaml` to point to the `.json` resources in example folder.
`msaf.yaml` is located at: `/usr/local/etc/open5gs/`

Intermediate solution is to prompt log message which will notify the user to change those paths in `msaf.yaml` manually.

Modifying the `meson` building process in order to initialize correct paths during installation, has to be considered.
