### ISSUE TITLE
Process additional domain name array when reserving a server certificate

### ISSUE THREAD

**Issue by rjb1000** [5G-MAG/rt-5gms-application-function#82]
TS 26.512 V17.6.0 clause 4.3.6.3 introduces the ability for the M1 requester to specify an array of domain name aliases when generating a Certificate Signing Request (CSR). These domain name aliases are then included as Subject Alternative Name(s) in the CSR returned by the 5GMS AF.

Clause 7.3.2 and C.3.2 specify the representation of these domain name aliases to be a JSON array in the `POST` request body of the `createOrReserveServerCertificate` operation.

This JSON array is only valid when the `csr` query parameter is supplied to this service operation.

Clause 4.3.6.2 specifies that it is not valid to supply domain name aliases when the 5GMS AF creates the server certificate on behalf of the 5GMS Application Provider. The OpenAPI YAML does not specify an error HTTP response code covering the case where the `csr` query parameter is absent but an array of domain name aliases is nevertheless supplied in the request HTTP message. It is recommended to return _400 Bad Request_ with a body containing `ProblemDetails` document explaining "Request message body permitted only when csr query parameter is present".

**Comment by davidjwbbc** [comment]
A quick review of the AF code base shows that this will impact the follow parts of the code:
- Application Function
-- M1 interface changes to accept a list domain name aliases in the body of new certificate reservation requests.
--- List of domain name aliases will be passed onto the certificate management script.
--  The default external Certificate Manager script will need to be modified to take a list of domain name aliases when generating a CSR to include in the SANs list.
--- Certificate management script requirements should be moved to the wiki as a reference for other implementations and include the alteration to take multiple domain name aliases.
- M1 client application (low level interface for testing/admin)
-- M1 client app will need to accept a list of domain name aliases on the command line for `certificate create`, but only if the `--csr` flag is also given.
- M1 session application (configuration tool)
-- `new-certificate` needs to take a list of domain name aliases that is not mutually exclusive with the `--csr` flag.
--- If no domain name aliases or `--csr` flag then the new certificate request is sent without the CSR flag and AF returns the certificate.
--- If one or more domain name aliases are given but no `--csr` flag, then the request for a new certificate is sent with the CSR flag present and the domain name aliases listed in the body, the M1 session app signs the returned CSR and stores the public certificate with the AF.
--- If the `--csr` flag is used, then the request is sent with the CSR flag present and the body contains a JSON array of any domain name aliases given (empty body should be sent if no domain name aliases given), the resulting CSR is sent to stdout.
- M1 client Python class (`rt_m1_client.client.M1Client`)
-- `M1Client.createOrReserveServerCertificate` needs to take an optional list of domain name alias strings to pass in the request.
--- Exception is thrown if domain name aliases list is not `None` or empty and the `csr` boolean is `False`.
-- `M1Client.reserveServerCertificate`  needs to take an optional list of domain name alias strings to pass in the request.
- M1 session Python class (`rt_m1_client.session.M1Session`)
-- `M1Session.certificateNewSigningRequest`  needs to take an optional list of domain name alias strings to pass in the request.
-- `M1Session.createNewCertificate` needs to take an optional list of domain name alias strings instead of just an optional single domain name alias.
-  Certificate Signers (`rt_m1_client.certificates.*`)
-- `signCertificate` methods can drop the `domain_name_alias` parameter as these will now be passed in the CSR.
--- These methods can also be simplified as they will no longer need manipulate the SANs and CommonName in the CSR.
-- `ACMECertificateSigner` class can drop the need for the private keys directory as it will no longer need to resign CSRs.

**Comment by davidjwbbc** [comment]
Made the changes and tested everything except the ACME certificates signer. I need to rig up a VM with public access to check this (so that Let's Encrypt can make the requests to verify the domain name).

**Comment by davidjwbbc** [comment]
Finally got the ACME bit tested and found a few bugs which I've fixed. I believe this is ready for a PR, however I also realised I've made the changes on top of some of our other pending changes for:
- Open5GS Rel 17 uplift (#60)
- BSF service consumer (#58)
- Network Assistance advertising over interface at M5 (#63)
- Change to AF M1+M5 Server headers (#80)

I'm happy to bundle them all up together as a stable update.

**Comment by rjb1000** [comment]
I'd be happy to bundle this change with #60 and #80, @davidjwbbc.

But I would prefer to keep #58 and #63 back until the BSF and PCF service consumer libraries have been contributed. (We still need to discuss the idea of setting up a separate new repository for these with @dsilhavy on his return from holiday.)

**Comment by davidjwbbc** [comment]
Ok, I'll cherry pick those changes onto a new branch and test.

**Comment by davidjwbbc** [comment]
Tests completed and PR #85 raised
